apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "grafana"
spec:
  deployment:
    spec:
      template:
        spec:
          volumes:
            - name: grafana-storage 
              persistentVolumeClaim:
                claimName: grafana            
          containers:
            - name: grafana
              volumeMounts:
                - name: grafana-storage 
                  mountPath: /var/lib/grafana                  
  config:
    log:
      mode: "console"
      level: "info"
