apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  project: default
  sources:


  - repoURL: git@github.com:marranz/k8s-local-env.git
    path: charts/grafana-operator-v5.20.0/
    helm:
      valueFiles:
        - $values/components/grafana-operator/helm-values.yaml

  - repoURL: git@github.com:marranz/k8s-local-env.git
    path: components/grafana-operator
    name: extra-manifests

  - repoURL: git@github.com:marranz/k8s-local-env.git
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

